national_total_costs:
  value:
    type: query
    data: value
    etm_key: total_costs

national_CO2_emissions_percentage:
  value:
    type: query
    data: value
    etm_key: dashboard_co2_emissions_versus_start_year

national_kpi_hv_network_load:
  value:
    type: query
    data: value
    etm_key: kpi_required_additional_hv_network_percentage

national_kpi_mv_network_load:
  value:
    type: query
    data: value
    etm_key: kpi_required_additional_mv_network_percentage

national_kpi_self_sufficiency:
  value:
    type: query
    data: value
    etm_key: kpi_self_sufficiency_local_production_of_primary_demand

national_renewability:
  value:
    type: query
    data: value
    etm_key: dashboard_renewability
